version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - stvnrlnd
  assignees:
  - stvnrlnd
  ignore:
  - dependency-name: algolia/algoliasearch-client-php
    versions:
    - 2.7.3
    - 2.8.0
    - 3.0.0
  - dependency-name: barryvdh/laravel-debugbar
    versions:
    - 3.5.2
    - 3.5.4
  - dependency-name: symfony/http-kernel
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: facade/ignition
    versions:
    - 1.16.16
    - 1.16.4
  - dependency-name: laravel/scout
    versions:
    - 8.6.0
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: predis/predis
    versions:
    - 1.1.6
  - dependency-name: mockery/mockery
    versions:
    - 1.3.3
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - stvnrlnd
  assignees:
  - stvnrlnd
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.10
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
